### ISSUE TITLE
Allowing Docker compose installation for Almalinux

### ISSUE THREAD

**Issue by Akshay-Hegde** [konstruktoid/ansible-role-docker-rootless#175]
https://github.com/konstruktoid/ansible-role-docker-rootless/blob/fd1739e085ac921bb8f39c944c57110f61436c10/tasks/main.yml#L41C29-L41C29

From
```
  when: docker_compose and ansible_os_family == "Debian"
```
To
```  
   when: docker_compose 
```
Can support Almalinux 9.2, I tested today.

Is there any specific reason why it is only supported for Debian as of now ?

**Comment by konstruktoid** [comment]
Hi @Akshay-Hegde and that is a very good question.
I'll have a look.

**Comment by konstruktoid** [comment]
Could you test https://github.com/konstruktoid/ansible-role-docker-rootless/pull/176?
