### ISSUE TITLE
Docker compose is hardcoded for x86_64

### ISSUE THREAD

**Issue by daladim** [konstruktoid/ansible-role-docker-rootless#402]
Thanks for this great and convenient Ansible role!

[This line](https://github.com/konstruktoid/ansible-role-docker-rootless/blob/c97da931091a89c5d098739586d81897a63f6f7d/tasks/docker_compose.yml#L29) hardcodes Docker-compose for x86_64 bits. I think that should be good to have an e.g. `docker_arch`  variable so that the caller can tweak it.

I just installed on an ARM server by manually downloading and overwriting the docker-compose executable. Sorry I did not take time to do an MR (I'll let you choose this variable name to avoid bikeshedding :D ) but that would be a great addition for this role

**Comment by konstruktoid** [comment]
Hi @daladim and thanks.
Adding an `arch` var makes a lot of sense, and I'll add it later today.

**Comment by daladim** [comment]
Thanks!
